### ISSUE TITLE
polarfs has already open source

### ISSUE THREAD

**Issue by mzygQAQ** [kernelai/pikafs#1]
https://github.com/ApsaraDB/PolarDB-FileSystem

**Comment by kernelai** [comment]
yes，it is. but it is a fs client . Alibaba didn't open source its polar store which is a distrubute file system.

**Comment by mzygQAQ** [comment]
> yes，it is. but it is a fs client . Alibaba didn't open source its polar store which is a distrubute file system.

I just downloaded the code. It is really just a client. Sorry to disturb you :)
